logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

spring:
  data.web:
    pageable:
      default-page-size: 20
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/lecture
    username: sa
    password:



