logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

spring:
  data.web:
    pageable:
      default-page-size: 20
  datasource:
    url: jdbc:mysql://localhost:3306/lecture
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lecture@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
